// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZwYpYl27yJtqxqkIDp__UTotumZ1TcTE',
    appId: '1:316424940438:web:077ec5ef3cf3c48f6c8bb7',
    messagingSenderId: '316424940438',
    projectId: 'habittrackerapp-14ff8',
    authDomain: 'habittrackerapp-14ff8.firebaseapp.com',
    storageBucket: 'habittrackerapp-14ff8.appspot.com',
    measurementId: 'G-70GJY2V6R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK6dz5sIVKpjHQnb_IeJHitMb03qsM2Do',
    appId: '1:316424940438:android:8cf8823639d2330c6c8bb7',
    messagingSenderId: '316424940438',
    projectId: 'habittrackerapp-14ff8',
    storageBucket: 'habittrackerapp-14ff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxOSYXnlb1TcOIXko1yQWxbBxqtXvklKw',
    appId: '1:316424940438:ios:e9f08eeacd5ce38e6c8bb7',
    messagingSenderId: '316424940438',
    projectId: 'habittrackerapp-14ff8',
    storageBucket: 'habittrackerapp-14ff8.appspot.com',
    iosBundleId: 'com.example.habittrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxOSYXnlb1TcOIXko1yQWxbBxqtXvklKw',
    appId: '1:316424940438:ios:e9f08eeacd5ce38e6c8bb7',
    messagingSenderId: '316424940438',
    projectId: 'habittrackerapp-14ff8',
    storageBucket: 'habittrackerapp-14ff8.appspot.com',
    iosBundleId: 'com.example.habittrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZwYpYl27yJtqxqkIDp__UTotumZ1TcTE',
    appId: '1:316424940438:web:57df24c2bdb10cf46c8bb7',
    messagingSenderId: '316424940438',
    projectId: 'habittrackerapp-14ff8',
    authDomain: 'habittrackerapp-14ff8.firebaseapp.com',
    storageBucket: 'habittrackerapp-14ff8.appspot.com',
    measurementId: 'G-3XZMQVFGCS',
  );
}
